#510 Remove plugin exports and update docs
website-scraper/node-website-scraper pull request #511
Opened 2022-09-17 11:19 UTC by ryanolee

# What
Removing plugin exports as discussed in #510 

# Why 
So that plugin code is not too tightly coupled to custom plugin implementations

# How
Remove plugin exports and updated documentation 

# Notes
Note: This should not be merged until V6

2022-09-18 11:35 UTC, ryanolee commented
Will fix the tests relating to this later today / tomorrow (time permitting 😆)

2022-09-20 20:10 UTC, s0ph1e requested changes
Hi @ryanolee

Thank you for creating the PR. Please fix the failing tests and update the readme according to the comments

2022-09-20 20:10 UTC, s0ph1e commented on README.md
> +- [website-scraper](#website-scraper)
There are too many changes here, could you please leave only plugins-related items?

2022-09-20 20:10 UTC, s0ph1e commented on README.md
>  Scraper has built-in plugins which are used by default if not overwritten with custom plugins. You can find them in [lib/plugins](https://github.com/website-scraper/node-website-scraper/tree/master/l
I think the documentation also needs an update here

2022-09-20 22:14 UTC, ryanolee commented
Hi @s0ph1e ,
Thanks for the reply! I think the extra changes the readme files came from one of my IDE extensions that annoyingly seems to run on pre commit. Removed the change for now and fixed up the tests / docs. Not sure what we want to do with this PR as it probably does not need to go out until v6 of the scraper. 👀

2022-09-21 20:26 UTC, s0ph1e commented
Hey @ryanolee,

Thank you for the quick changes. I'm going to merge the PR to master (master stands for current WIP for the next version, v5 code will be in branch 5.x)

2022-09-21 20:28 UTC, merged